/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    val contact = Contact("Ahla", 19, true)
    contact.print()
}
